---
- name: Copy docker-compose file to remote
  template:
    src: docker-compose.yml
    dest: "{{ docker_compose_file }}"
  when: inventory_hostname != 'localhost'

- name: Run Docker Compose on localhost
  command: docker compose -f /var/lib/jenkins/workspace/ChatApp/Deployment/roles/docker/templates/docker-compose.yml up -d
  when: inventory_hostname == 'localhost'
# Uncomment for remote hosts
# - name: Run Docker Compose on remote
#   command: docker-compose -f "{{ docker_compose_file }}" up -d
#   when: inventory_hostname != 'localhost'
