---
- name: Set KUBECONFIG environment variable
  environment:
    KUBECONFIG: /home/yukta/.kube/config

- name: Apply Kubernetes Manifests
  command: kubectl apply -f {{ playbook_dir }}/roles/kubernetes/files/{{ item }}
  with_items:
    - backend-deployment.yaml
    - backend-service.yaml
    - frontend-deployment.yaml
    - frontend-service.yaml
