---
- name: Apply Kubernetes Manifests
  command: kubectl apply -f {{ item }}
  with_items:
    - backend-deployment.yaml
    - backend-service.yaml
    - frontend-deployment.yaml
    - frontend-service.yaml
