---
- name: Pull Docker Images and Run Docker Compose
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    docker_compose_file: /home/{{ ansible_user }}/docker-compose.yml
  tasks:
    - name: Pull backend image
      docker_image:
        name: yuktax/backend:latest
        source: pull

    - name: Pull frontend image
      docker_image:
        name: yuktax/frontend:latest
        source: pull

    - name: Copy docker-compose file to remote
      copy:
        src: ../docker-compose.yml
        dest: "{{ docker_compose_file }}"
      when: inventory_hostname != 'localhost'

    - name: Run Docker Compose on localhost
      command: docker compose -f ../docker-compose.yml up -d
      when: inventory_hostname == 'localhost'

    - name: Apply Kubernetes Manifests
      command: kubectl apply -f {{ item }}
      with_items:
        - backend-deployment.yaml
        - backend-service.yaml
        - frontend-deployment.yaml
        - frontend-service.yaml

    - name: Apply HPA Manifests
      command: kubectl apply -f {{ item }}
      with_items:
        - backend-hpa.yaml
        - frontend-hpa.yaml

    # The following is for clean-up.
    # Not sure if it will work correctly

    # - name: Clean Kubernetes Manifests
    #   command: kubectl delete -f {{ item }}
    #   with_items:
    #     - backend-deployment.yaml
    #     - backend-service.yaml
    #     - frontend-deployment.yaml
    #     - frontend-service.yaml

    # - name: Run Docker Compose on remote
    #   command: docker-compose -f "{{ docker_compose_file }}" up -d
    #   when: inventory_hostname != 'localhost'
